import {
  extractId as googleDocsExtractId,
  exchangeCode as googleDocsExchangeCode,
  getIdentity as googleDocsGetIdentity,
  getMetadata as googleDocsGetMetadata,
  validateDomain as googleDocsValidateDomain,
  refreshTokenIfNeeded as googleDocsRefreshTokenIfNeeded,
  createDocument as googleDocsCreateDocument,
} from './google-docs.js'
import {
  extractId as notionExtractId,
  exchangeCode as notionExchangeCode,
  getIdentity as notionGetIdentity,
  getMetadata as notionGetMetadata,
  validateDomain as notionValidateDomain,
  createDocument as notionCreateDocument,
} from './notion.js'

export const PROVIDERS = {
  'google-docs': {
    configKey: 'google_docs',
    urlPattern: /docs\.google\.com\/document\/d\//,
    supportsRefresh: true,
    domainField: 'allowed_domain',
    authUrl: 'https://accounts.google.com/o/oauth2/v2/auth',
    scopes: [
      'https://www.googleapis.com/auth/drive.metadata.readonly',
      'https://www.googleapis.com/auth/drive.file',
    ],
    authParams: { access_type: 'offline', prompt: 'consent' },
    enrichToken: null,
    extractId: googleDocsExtractId,
    exchangeCode: googleDocsExchangeCode,
    getIdentity: googleDocsGetIdentity,
    getMetadata: googleDocsGetMetadata,
    validateDomain: googleDocsValidateDomain,
    refreshTokenIfNeeded: googleDocsRefreshTokenIfNeeded,
    createDocument: googleDocsCreateDocument,
  },
  'notion': {
    configKey: 'notion',
    urlPattern: /notion\.so\//,
    supportsRefresh: false,
    domainField: 'allowed_workspace',
    authUrl: 'https://api.notion.com/v1/oauth/authorize',
    scopes: [],
    authParams: { owner: 'user' },
    enrichToken: null,
    extractId: notionExtractId,
    exchangeCode: notionExchangeCode,
    getIdentity: notionGetIdentity,
    getMetadata: notionGetMetadata,
    validateDomain: notionValidateDomain,
    refreshTokenIfNeeded: null,
    createDocument: notionCreateDocument,
  },
}
